---
# Ansible script to do clean restart weblogic on target servers.
#Usage: ansible-playbook -i inventory Liferayweblogicstatus.yml -l <envType>
#Usage: ansible-playbook -i inventory Liferayweblogucstatus.yml -l DEV
##power devops-

- hosts: all
  remote_user: '{{ mi_user }}'
  become: yes
  become_user: oracle
  become_method: sudo

  vars_files:
    - ./vars/passwd.yml

  tasks:

    - include: node1.yml
      delegate_to: "{{ item }}"
      with_items: ${groups.liferayDEV01_Node1}

    - include: node2.yml
      delegate_to: "{{ item }}"
      with_items: ${groups.liferayDEV01_Node2}
